Iter13
Tokebay/yandex pull request #13
Opened 2023-09-17 13:56 UTC by Tokebay

2023-09-18 17:58 UTC, popoffvg requested changes

2023-09-18 17:58 UTC, popoffvg commented on internal/app/storage/storage.go
> +	rowsAffected, _ := result.RowsAffected()
[major]

Не стоит игнорировать ошибки. Потом можно очень долго искать, а что же не работает

2023-09-18 17:58 UTC, popoffvg commented on internal/app/storage/storage.go
> +	CREATE TABLE IF NOT EXISTS public.shorten_urls
[minor]

Стоило воспользоваться библиотеками для накатки миграций

2023-09-18 17:58 UTC, popoffvg commented on internal/app/handlers/batch.go
> +			pgStorage, err := storage.NewPostgreSQLStorage(cfg.DSN)
[major]

Не стоит создавать экземпляр базы на каждый запрос. И не стоит создавать соединение на каждый запрос. Для postgres создание соединение с базой очень дорогая операция. Стоит воспользоваться драйвером pgx и пулом соединений

2023-09-18 17:58 UTC, popoffvg commented on internal/app/storage/storage.go
> +func (s *PostgreSQLStorage) ExistOrigURL(origURL string) string {
[minor]

Этот метод не нужен, т.к. всю работу выполняет уникальный индекс. При этом в случае || этот метод не гарантирует корректной работы

2023-09-18 17:58 UTC, popoffvg commented on internal/app/storage/storage.go
> +	if err != nil && err != sql.ErrNoRows {
[major]

Неправильно обрабатывать ошибку только в том случае, если это ошибка "нет строк в результате". Могут быть еще проблемы при соединение с БД

2023-09-21 04:43 UTC, Tokebay commented on internal/app/storage/storage.go
> +	CREATE TABLE IF NOT EXISTS public.shorten_urls
Не получается воспользоваться migrate. поставил вопрос в группу group3.

2023-09-21 14:41 UTC, Tokebay commented on internal/app/storage/storage.go
> +func (s *PostgreSQLStorage) ExistOrigURL(origURL string) string {
что значит ||  ?

2023-09-21 17:52 UTC, Tokebay commented on internal/app/storage/storage.go
> +	CREATE TABLE IF NOT EXISTS public.shorten_urls
с migrate, так и не смог разобраться, и понять что не так. выдает ошибку когда локально запускаю no scheme.

2023-09-26 18:15 UTC, merged