Iter9
Tokebay/yandex pull request #9
Opened 2023-08-29 19:02 UTC by Tokebay

2023-09-04 18:02 UTC, popoffvg requested changes

2023-09-04 18:02 UTC, popoffvg commented on internal/app/gzip.go
> +		if supportsGzip && contentType == "application/json" || contentType == "text/html" {
[minor]

Ограничение на content-type тут лишнее, т.к. для gzip не важен формат передаваемых данных

2023-09-04 18:02 UTC, popoffvg commented on internal/app/producer.go
> +	p.buffer = append(p.buffer, *urlData)
[major]

1.  Не гарантируется уникальность ссылок в отличии от memory хранилища
2. Данные на диск будут сохранены не корректные, т.к. не учитываются данные, прочитанные из файла при старте

2023-09-04 18:02 UTC, popoffvg commented on internal/app/shortener.go
> +		http.Error(w, "error creating JSON response", http.StatusInternalServerError)
[major]


Забыл return

2023-09-04 18:02 UTC, popoffvg commented on internal/app/producer.go
> +	p.buffer = nil
[major]

Буфер тут не нужен, т.к. после добавления в буфер всегда идет запись на диск. 
В добавок не гарантируется, что во время Flush не будет вызван SaveToFileURL (из хендлера)

Лучше получать данные из inmemory хранилища и записывать. Тогда не будет проблем с конкурентным доступом.

2023-09-07 15:03 UTC, Tokebay commented on internal/app/gzip.go
> +		if supportsGzip && contentType == "application/json" || contentType == "text/html" {
в задаче инкремента 8 стояло условие, что "Функция сжатия должна работать для контента с типами application/json и text/html."

2023-09-08 06:00 UTC, popoffvg commented on internal/app/gzip.go
> +		if supportsGzip && contentType == "application/json" || contentType == "text/html" {
Ага, но у тебя мидлвара обрабатывает gzip. Не её ответсвенность еще и тип проверять

2023-09-08 06:01 UTC, popoffvg approved these changes

2023-09-10 08:43 UTC, merged